import { useState } from "react";
import { useParams, Link as RouterLink } from "react-router-dom";
import {
  Stack, Typography, Box, Button, LinearProgress, Alert,
  Paper, Breadcrumbs, Link, Snackbar, CircularProgress,
} from "@mui/material";
import useReportStream from "../hooks/useReportStream";
import { api } from "../services/api";

function ReportPage() {
  const { drugId } = useParams<{ drugId: string }>();
  const [markdown, setMarkdown] = useState("");
  const [toast, setToast] = useState("");
  const [docxLoading, setDocxLoading] = useState(false);
  const [started, setStarted] = useState(false);

  const { status, progress, message, error, start } = useReportStream({
    drugId: drugId ?? "",
    onComplete: setMarkdown,
  });

  const handleStart = () => {
    setStarted(true);
    setMarkdown("");
    start();
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(markdown);
    setToast("Report copied to clipboard");
  };

  const handleDownloadTxt = () => {
    const blob = new Blob([markdown], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `drug_report_${drugId}.txt`;
    a.click();
  };

  const handleDownloadDocx = async () => {
    if (!markdown) return;
    setDocxLoading(true);
    try {
      const res = await api.post(
        `/api/v1/ai/download-docx/${drugId}`,
        { report: markdown },
        { responseType: "blob" }
      );
      const blob = new Blob([res.data], {
        type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      });
      const a = document.createElement("a");
      a.href = URL.createObjectURL(blob);
      a.download = `drug_report_${drugId}.docx`;
      a.click();
    } catch {
      setToast("Failed to download DOCX");
    } finally {
      setDocxLoading(false);
    }
  };

  const isRunning = status === "starting" || status === "generating";

  return (
    <Stack spacing={3}>
      <Breadcrumbs>
        <Link component={RouterLink} to="/" underline="hover" color="inherit">Drugs</Link>
        {drugId && (
          <Link component={RouterLink} to={`/drugs/${drugId}`} underline="hover" color="inherit">
            Drug Detail
          </Link>
        )}
        <Typography color="text.primary">AI Report</Typography>
      </Breadcrumbs>

      <Box
        sx={{
          background: "linear-gradient(135deg, #7c3aed, #4f46e5)",
          borderRadius: 2,
          p: 3,
          color: "#fff",
        }}
      >
        <Typography variant="h5" fontWeight={700} gutterBottom>
          AI-Powered Regulatory Comparison Report
        </Typography>
        <Typography variant="body2" mb={2}>
          Generated by Anthropic Claude 3.5 Sonnet · Cross-country label analysis
        </Typography>

        <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap>
          <Button
            variant="contained"
            onClick={handleStart}
            disabled={isRunning}
            sx={{ bgcolor: "rgba(255,255,255,0.2)", "&:hover": { bgcolor: "rgba(255,255,255,0.35)" } }}
          >
            {isRunning && <CircularProgress size={16} sx={{ color: "#fff", mr: 1 }} />}
            {isRunning ? "Generating..." : started ? "Regenerate Report" : "Generate AI Report"}
          </Button>

          {markdown && (
            <>
              <Button
                variant="outlined"
                onClick={handleCopy}
                sx={{ color: "#fff", borderColor: "rgba(255,255,255,0.5)" }}
              >
                Copy
              </Button>
              <Button
                variant="outlined"
                onClick={handleDownloadTxt}
                sx={{ color: "#fff", borderColor: "rgba(255,255,255,0.5)" }}
              >
                Download TXT
              </Button>
              <Button
                variant="outlined"
                onClick={handleDownloadDocx}
                disabled={docxLoading}
                sx={{ color: "#fff", borderColor: "rgba(255,255,255,0.5)" }}
              >
                {docxLoading ? <CircularProgress size={16} sx={{ color: "#fff", mr: 1 }} /> : null}
                Download DOCX
              </Button>
            </>
          )}
        </Stack>
      </Box>

      {isRunning && (
        <Box>
          <Typography variant="body2" color="text.secondary" gutterBottom>
            {message}
          </Typography>
          <LinearProgress
            variant={progress > 0 ? "determinate" : "indeterminate"}
            value={progress}
          />
        </Box>
      )}

      {error && <Alert severity="error">{error}</Alert>}

      {!started && !markdown && (
        <Alert severity="info">
          Click "Generate AI Report" to create a cross-country regulatory comparison. This takes 20–40 seconds.
        </Alert>
      )}

      {markdown && (
        <Paper elevation={1} sx={{ p: { xs: 2, md: 4 } }}>
          <Box
            sx={{
              "& h1": { fontSize: "1.7rem", fontWeight: 800, mt: 2, mb: 1, borderBottom: "3px solid", borderColor: "primary.main", pb: 0.5 },
              "& h2": { fontSize: "1.35rem", fontWeight: 700, mt: 2.5, mb: 1, color: "primary.dark" },
              "& h3": { fontSize: "1.1rem", fontWeight: 600, mt: 2, mb: 0.5 },
              "& h4": { fontSize: "1rem", fontWeight: 600, mt: 1.5 },
              "& p": { mb: 1.5, lineHeight: 1.8 },
              "& ul, & ol": { pl: 3, mb: 1.5 },
              "& li": { mb: 0.5, lineHeight: 1.7 },
              "& strong": { fontWeight: 700 },
              "& em": { fontStyle: "italic" },
              "& hr": { my: 2.5, borderColor: "divider" },
              "& table": { borderCollapse: "collapse", width: "100%", mb: 2, fontSize: "0.875rem" },
              "& th": { bgcolor: "primary.main", color: "#fff", p: "8px 12px", fontWeight: 700, textAlign: "left" },
              "& td": { border: "1px solid", borderColor: "divider", p: "6px 12px", verticalAlign: "top" },
              "& tr:nth-of-type(even)": { bgcolor: "action.hover" },
              "& blockquote": { borderLeft: "4px solid", borderColor: "primary.light", pl: 2, ml: 0, color: "text.secondary" },
            }}
            dangerouslySetInnerHTML={{ __html: renderMarkdown(markdown) }}
          />
        </Paper>
      )}

      <Snackbar
        open={!!toast}
        autoHideDuration={3000}
        onClose={() => setToast("")}
        message={toast}
      />
    </Stack>
  );
}

function renderMarkdown(md: string): string {
  // Escape HTML
  let html = md
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  // Block elements
  html = html
    .replace(/^#### (.+)$/gm, "<h4>$1</h4>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/^---+$/gm, "<hr>")
    .replace(/^\*\*\*+$/gm, "<hr>");

  // Tables (simple)
  html = html.replace(/^\|(.+)\|$/gm, (line) => {
    if (line.includes("---")) return "";
    const cells = line.split("|").slice(1, -1).map((c) => c.trim());
    return "<tr>" + cells.map((c) => `<td>${c}</td>`).join("") + "</tr>";
  });
  html = html.replace(/(<tr>.*<\/tr>\n?)+/gs, (t) => `<table>${t}</table>`);

  // Inline
  html = html
    .replace(/\*\*\*(.+?)\*\*\*/g, "<strong><em>$1</em></strong>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`(.+?)`/g, "<code>$1</code>");

  // Lists
  html = html.replace(/^[-*] (.+)$/gm, "<li>$1</li>");
  html = html.replace(/^\d+\. (.+)$/gm, "<li>$1</li>");
  html = html.replace(/(<li>[\s\S]+?<\/li>)(\n(?!<li>)|$)/g, "<ul>$1</ul>$2");

  // Paragraphs
  html = html
    .split(/\n\n+/)
    .map((block) => {
      if (/^<(h[1-4]|ul|ol|li|hr|table|tr|blockquote)/.test(block.trim())) return block;
      if (block.trim() === "") return "";
      return `<p>${block.replace(/\n/g, "<br>")}</p>`;
    })
    .join("\n");

  return html;
}

export default ReportPage;
